/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class HolaJNI */

#ifndef _Included_HolaJNI
#define _Included_HolaJNI
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     HolaJNI
 * Method:    diHola
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_HolaJNI_diHola
  (JNIEnv *, jobject);

#ifdef __cplusplus
}
#endif
#endif
